baseURL = 'https://zvictorliu.github.io/computer_networking/'
languageCode = 'en-us'
title = 'Computer Networking'

theme = 'book'

[markup]
 [markup.goldmark.renderer]
  unsafe = true

 [markup.tableOfContents]
  startLevel = 2

[menu]
# [[menu.before]]
[[menu.after]]
  name = "Github"
  url = "https://github.com/zvictorliu/computer_networking"
  weight = 10

[[menu.after]]
  name = "Hugo Themes"
  url = "https://themes.gohugo.io/hugo-book/"
  weight = 20

[params]
	BookTheme = 'light'
	BookToC = true
	BookLogo = 'https://cdn.jsdelivr.net/gh/zvictorliu/typoraPics@main/img/3d-wifi.png'
	BookRepo = 'https://github.com/zvictorliu/computer_networking'
	BookSection = '*'

	BookSearch = true
	BookComments = true

  BookCommitPath = 'commit'
  BookDateFormat = 'January 2, 2006'

